### PR TITLE
Added additional configuration options

### PR DESCRIPTION
**Pull request by myovchev**
Additional configuration options - bot name, icon url and channel/direct message.

sentry-slack-preview

### CODE REVIEW

**Comment by dcramer** [comment]
I think these are things we'd likely want to configure at the system level than per project

**Comment by myovchev** [comment]
I can't see system level configuration to fit most of the people needs, but it could be just me. Scenarios like single Slack token for multiple team channels, re-branded bot icon/name per application... It just sounds reasonable to me. 

I'll fix the build errors anyway.

**Comment by dcramer** [comment]
I'll agree this doesnt hurt. I dont see the need for Sentry being named differently in different rooms, but even in an ideal world we'd likely want to provide something to customize this under advanced configuration.

**Comment by dcramer** [comment]
Also regarding channel, I guess this means the webhook isn't channel bound? I thought this was actually how the Slack hooks worked, though I know we talked about making it so a single project could hit multiple slack channels.

**Comment by myovchev** [comment]
Slack is binding to default channel, yes. The idea is if bot doesn't override the 'channel' payload, message ends to the default one. Integrations on (free) Slack are limited, so using one webhook for all team integrations is pretty much worth :)

**Pull request merged**
