### PR TITLE
Added ability to send events to different channels depending on the value of a tag

### PR DESCRIPTION
**Pull request by Eredian**
This is something we required to send events coming from different portions of the same application to the right team in slack.

Provides configuration so that a specific tag can be used to direct the events to the right channel depending on that tag's value.

---

This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-slack/43)

### CODE REVIEW

**Comment by jebeaudet** [comment]
Would love to see this merged, we need it on our end as well.

**Comment by fredboutin** [comment]
Nice PR you should merge this!

**Comment by mjdavies** [comment]
Merge the beast, please!! We'd love to see this functionality, it would stop a load of people whinging about sentry in our organisation. Whingers do my nut in

**Comment by evanpurkhiser** [comment]
[The new slack integration supports this!](https://blog.sentry.io/2018/04/02/sentry-plus-slack)

**Pull request closed without merging**
